name: BioSignals-MinecraftLayer
version: 1.0-SNAPSHOT
main: il.co.biosignals.minecraftlayer.MinecraftLayer
api-version: 1.19
depend: [DecentHolograms]
commands:
  biosignals:
    description: The main command for biosignals.
    usage: /<command> [uuid|request]
    permission: biosignals.biosignals_command
    permission-message: Permission denied.
permissions:
  biosignals.all:
    children:
      biosignals.biosignals_command:
        default: true
      biosignals.biosignals_command.all:
        children:
          biosignals.biosignals_command.uuid:
            default: true
          biosignals.biosignals_command.request:
            default: true
          biosignals.biosignals_command.test:
            default: op